#!/usr/bin/env bash
# One-time (idempotent) pgBackRest setup: backups go STRAIGHT TO R2, never to
# the local disk.
#
# Why this exists — three disk-full incidents in nine days (2026-08-06, 08-07,
# 08-11..14), every one of them a failure of hand-written retention arithmetic
# on a filesystem shared with PGDATA:
#   - WAL archive, nightly dumps and base backups all landed on the same 38GB
#     volume as the live database, so a backup overrun stopped Postgres writing.
#   - Three bespoke scripts (archive-wal.sh, prune-wal-cap.sh,
#     backup-basebackup.sh) each enforced a defensible cap, and nobody ever
#     summed them against the disk. One of them was dead config for a month.
#
# pgBackRest removes the category rather than re-tuning the numbers: the repo
# lives in object storage, where retention is elastic and enforced by the tool.
# It also closes a real durability hole — until now WAL and base backups existed
# in exactly ONE place, the disk they were protecting. A disk failure lost PITR
# outright.
#
# Safe to re-run: rewrites the config and re-checks the stanza. It does NOT
# change archive_command (see 35-recrutas-archive.conf) — that cutover is
# deliberate and separate, so this can be staged without touching recovery.
set -uo pipefail

APP_DIR="${RECRUTAS_DIR:-/opt/recrutas/app}"
STANZA="${PGBACKREST_STANZA:-main}"
PG_PATH="${PGDATA_PATH:-/var/lib/postgresql/17/main}"
CONF=/etc/pgbackrest/pgbackrest.conf
BUCKET="${PGBACKREST_BUCKET:-recrutas-backups}"

cd "$APP_DIR" || { echo "[setup-pgbackrest] cannot cd $APP_DIR" >&2; exit 1; }
set -a; # shellcheck disable=SC1091
source .env; set +a

need() { command -v "$1" >/dev/null || { echo "[setup-pgbackrest] missing $1" >&2; exit 1; }; }
need pgbackrest
need rclone

# Credentials are read from the rclone remote that offsite-backup.sh already
# uses, rather than being duplicated into a second place that can drift out of
# sync with it. One set of R2 keys, one place to rotate them.
r2() { rclone config show r2 2>/dev/null | sed -n "s/^$1 *= *//p" | head -1; }
S3_KEY="$(r2 access_key_id)"
S3_SECRET="$(r2 secret_access_key)"
S3_ENDPOINT="$(r2 endpoint | sed -E 's#^https?://##')"

[ -n "$S3_KEY" ] && [ -n "$S3_SECRET" ] && [ -n "$S3_ENDPOINT" ] || {
  echo "[setup-pgbackrest] could not read R2 credentials from 'rclone config show r2'" >&2
  exit 1
}

# Repo encryption. Derived from the EXISTING GPG passphrase rather than being a
# new independent secret, deliberately: the passphrase is already the one thing
# that must survive for offsite backups to be restorable, and adding a second
# such secret would double the number of ways to permanently lose recoverability.
# Recompute at any time with:
#   printf '%s' "$OFFSITE_GPG_PASSPHRASE" | sha256sum
#
# ⚠️ If OFFSITE_GPG_PASSPHRASE is ever rotated, EVERY pgBackRest backup taken
# before the rotation becomes undecryptable. Do not rotate it.
[ -n "${OFFSITE_GPG_PASSPHRASE:-}" ] || {
  echo "[setup-pgbackrest] OFFSITE_GPG_PASSPHRASE unset in .env — refusing to configure an unencrypted repo" >&2
  exit 1
}
CIPHER_PASS="$(printf '%s' "$OFFSITE_GPG_PASSPHRASE" | sha256sum | cut -d' ' -f1)"

install -d -m 0750 -o postgres -g postgres /var/log/pgbackrest /var/lib/pgbackrest
# Group postgres, not root: pgbackrest runs as postgres and needs to traverse
# this directory to read the config. 0750 root:root here fails with a bare
# "[041]: unable to open file ... Permission denied" that reads like a problem
# with the file rather than the directory above it.
install -d -m 0750 -o root -g postgres /etc/pgbackrest

# 0640 root:postgres — postgres must read it (archive-push runs as postgres),
# nothing else should. Written via a temp file so a failure here cannot leave a
# half-written config that breaks archiving.
umask 027
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
cat > "$TMP" <<EOF
# Generated by infra/vps/setup-pgbackrest.sh — do not hand-edit.
# Contains R2 credentials and the repo encryption passphrase.
[global]
repo1-type=s3
repo1-s3-bucket=${BUCKET}
repo1-s3-endpoint=${S3_ENDPOINT}
repo1-s3-region=auto
repo1-s3-key=${S3_KEY}
repo1-s3-key-secret=${S3_SECRET}
# R2 requires path-style addressing; virtual-host style 404s against the
# account endpoint.
repo1-s3-uri-style=path
repo1-path=/pgbackrest

repo1-cipher-type=aes-256-cbc
repo1-cipher-pass=${CIPHER_PASS}

# Retention. Weekly full + daily incremental, keeping 2 fulls => 7-14 days of
# PITR depth. The previous local setup managed ~1-2 days before it hit the disk.
# WAL is retained automatically back to the oldest retained full backup, so
# there is no separate WAL cap to keep in sync — the class of bug that caused
# all three disk-full incidents cannot recur here.
repo1-retention-full=2
repo1-retention-diff=4

# Bundle small files into larger objects: R2 bills per-operation, and a backup
# of a 185K-row job board is mostly small relation files.
repo1-bundle=y
compress-type=zst
compress-level=6
process-max=2

log-level-console=info
log-level-file=detail
log-path=/var/log/pgbackrest
start-fast=y

[${STANZA}]
pg1-path=${PG_PATH}
pg1-port=5432
EOF

install -m 0640 -o root -g postgres "$TMP" "$CONF"
rm -f "$TMP"; trap - EXIT
echo "[setup-pgbackrest] wrote $CONF (repo s3://${BUCKET}/pgbackrest, encrypted, retention 2 full)"

# stanza-create is idempotent; stanza-upgrade covers a PG major-version bump.
# Capture rather than pipe: piping into grep makes $? the GREP's status, which
# silently swallowed a hard "Permission denied" here and still printed "ready".
OUT="$(sudo -u postgres pgbackrest --stanza="$STANZA" stanza-create 2>&1)"; RC=$?
printf '%s\n' "$OUT"
if [ "$RC" -ne 0 ]; then
  if printf '%s' "$OUT" | grep -qiE 'already exists|stanza-upgrade'; then
    sudo -u postgres pgbackrest --stanza="$STANZA" stanza-upgrade \
      || { echo "[setup-pgbackrest] stanza-upgrade failed" >&2; exit 1; }
  else
    echo "[setup-pgbackrest] stanza-create failed (rc=$RC) — see output above" >&2
    exit 1
  fi
fi

echo "[setup-pgbackrest] stanza '$STANZA' ready"
echo
echo "NEXT: archive_command must point at pgbackrest before any backup can"
echo "complete — pgbackrest backup waits for its start WAL to reach the repo."
echo "  1) infra/vps/cutover-pgbackrest.sh   (dual-writes local + R2)"
echo "  2) sudo -u postgres pgbackrest --stanza=$STANZA check"
echo "  3) bash infra/vps/pgbackrest-backup.sh full"
