import { useMemo, useState } from "react";
import { ChevronDown, ChevronLeft, ChevronRight, Download, Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import {
  REQUIRED_PER_WEEK, claimWeek, logEntriesForWeek, logToCsv, mmddyyyy,
  type LoggableApplication, type LogEntry,
} from "@/lib/job-search-log";

const esc = (s: string) => s.replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]!));

function printLog(entries: LogEntry[], weekEnding: Date) {
  const w = window.open("", "_blank");
  if (!w) {return;}
  const rows = entries.map((e, i) => `<tr><td>${i + 1}</td><td>${e.contactDate}</td><td>${esc(e.jobTitle)}</td><td>${esc(e.employer)}</td>
    <td>${e.method}</td><td>${e.contactType}</td><td></td><td>${esc(e.city)}</td><td>${esc(e.state)}</td><td>${esc(e.website)}</td><td></td></tr>`).join("");
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Job-search log, week ending ${mmddyyyy(weekEnding)}</title>
    <style>body{font:12px system-ui,sans-serif;margin:24px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #999;padding:4px 6px;text-align:left;vertical-align:top}th{background:#eee}</style></head>
    <body><h2>Job-search log for week ending ${mmddyyyy(weekEnding)}</h2>
    <p>Name: ______________________ &nbsp; ID: ____________ &nbsp; All entries are employer contacts.</p>
    <table><thead><tr><th>#</th><th>Contact date</th><th>Job title</th><th>Employer</th><th>How</th><th>Type</th><th>Address</th><th>City</th><th>State</th><th>Website or email</th><th>Phone</th></tr></thead>
    <tbody>${rows}</tbody></table>
    <p>Complete the address and phone for each employer before submitting. Generated by Recrutas from your tracked applications.</p></body></html>`);
  w.document.close();
  w.focus();
  w.print();
}

function downloadCsv(entries: LogEntry[], weekEnding: Date) {
  const blob = new Blob([logToCsv(entries, weekEnding)], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `job-search-log-${mmddyyyy(weekEnding).replace(/\//g, "-")}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

const OPEN_KEY = "recrutas_job_search_log_open";
const readOpen = (): boolean => { try { return localStorage.getItem(OPEN_KEY) === "1"; } catch { return false; } };

/**
 * The week's applications as an unemployment job-search log (Washington ESD's
 * fields). Recrutas fills in what it knows; the claimant completes the rest.
 * Folded to one line by default (most candidates aren't claiming); whoever
 * opens it finds it open next time.
 */
export function JobSearchLog({ applications }: { applications: LoggableApplication[] }) {
  const [weekOf, setWeekOf] = useState(() => new Date());
  const { weekEnding } = claimWeek(weekOf);
  const entries = useMemo(() => logEntriesForWeek(applications, weekOf), [applications, weekOf]);
  const shift = (days: number) => setWeekOf(d => new Date(d.getFullYear(), d.getMonth(), d.getDate() + days));
  const isCurrentWeek = claimWeek(new Date()).weekEnding.getTime() === weekEnding.getTime();
  const met = entries.length >= REQUIRED_PER_WEEK;
  const [open, setOpen] = useState(readOpen);
  const toggle = () => setOpen(o => {
    try { localStorage.setItem(OPEN_KEY, o ? "0" : "1"); } catch { /* storage blocked */ }
    return !o;
  });

  if (!open) {
    return (
      <Card data-testid="job-search-log">
        <button type="button" onClick={toggle} aria-expanded={false}
          className="w-full flex items-center justify-between gap-3 p-4 sm:px-5 text-left hover:bg-slate-50 dark:hover:bg-slate-900 rounded-lg">
          <span>
            <span className="block text-base font-semibold text-slate-900 dark:text-slate-100">Job-search log for unemployment</span>
            <span className="block text-sm text-slate-500 dark:text-slate-400">Filling a weekly claim? Your applications, ready as a CSV or printable log.</span>
          </span>
          <ChevronDown className="h-4 w-4 shrink-0 text-slate-400" />
        </button>
      </Card>
    );
  }

  return (
    <Card data-testid="job-search-log">
      <CardContent className="p-4 sm:p-5 space-y-3">
        <div className="flex flex-wrap items-center justify-between gap-2">
          <button type="button" onClick={toggle} aria-expanded className="flex items-center gap-2 text-left">
            <h3 className="text-base font-semibold text-slate-900 dark:text-slate-100">Job-search log for unemployment</h3>
            <ChevronDown className="h-4 w-4 rotate-180 text-slate-400" />
          </button>
          <div className="flex items-center gap-1">
            <Button variant="ghost" size="sm" onClick={() => shift(-7)} aria-label="Previous week"><ChevronLeft className="h-4 w-4" /></Button>
            <span className="text-sm tabular-nums">Week ending {mmddyyyy(weekEnding)}</span>
            <Button variant="ghost" size="sm" onClick={() => shift(7)} disabled={isCurrentWeek} aria-label="Next week"><ChevronRight className="h-4 w-4" /></Button>
          </div>
        </div>
        <p className={`text-sm ${met ? "text-emerald-700 dark:text-emerald-400" : "text-slate-700 dark:text-slate-300"}`} data-testid="job-search-log-status">
          {entries.length} of {REQUIRED_PER_WEEK} employer contacts this week{met ? ". Weekly minimum met" : ""}.
          <span className="text-slate-500 dark:text-slate-400"> Washington asks for {REQUIRED_PER_WEEK} activities a week; other states differ.</span>
        </p>
        {entries.length > 0 && (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="text-left text-slate-500 dark:text-slate-400">
                <tr><th className="py-1 pr-3 font-medium">Date</th><th className="py-1 pr-3 font-medium">Job title</th><th className="py-1 pr-3 font-medium">Employer</th><th className="py-1 pr-3 font-medium">How / type</th><th className="py-1 font-medium">City, state</th></tr>
              </thead>
              <tbody className="text-slate-800 dark:text-slate-200">
                {entries.map((e, i) => (
                  <tr key={i} className="border-t border-slate-100 dark:border-slate-800">
                    <td className="py-1.5 pr-3 tabular-nums whitespace-nowrap">{e.contactDate}</td>
                    <td className="py-1.5 pr-3">{e.jobTitle}</td>
                    <td className="py-1.5 pr-3">{e.employer}</td>
                    <td className="py-1.5 pr-3 whitespace-nowrap">{e.method} · {e.contactType}</td>
                    <td className="py-1.5">{e.city ? `${e.city}, ${e.state}` : <span className="text-slate-400">add</span>}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
        <div className="flex flex-wrap items-center gap-2">
          <Button size="sm" variant="outline" onClick={() => downloadCsv(entries, weekEnding)} disabled={!entries.length}><Download className="h-4 w-4 mr-1.5" />Download CSV</Button>
          <Button size="sm" variant="outline" onClick={() => printLog(entries, weekEnding)} disabled={!entries.length}><Printer className="h-4 w-4 mr-1.5" />Print</Button>
        </div>
        <p className="text-xs text-slate-500 dark:text-slate-400">
          Built from the applications Recrutas tracked. Add each employer's address and phone (and any missing city) before you submit: your log is your responsibility, and the state may verify it.
        </p>
      </CardContent>
    </Card>
  );
}
